In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
%matplotlib inline
from pathlib import Path
import pandas as pd
import scipy.stats as stats
import os

In [3]:
df = Path('Data/airlines_2005_1.csv')

df = pd.read_csv(df)

df.head()

,ActualElapsedTime,AirTime,ArrDelay,ArrTime,CRSArrTime,CRSDepTime,CRSElapsedTime,CancellationCode,Cancelled,CarrierDelay,...,Month,NASDelay,Origin,SecurityDelay,TailNum,TaxiIn,TaxiOut,UniqueCarrier,WeatherDelay,Year
0,49.0,37.0,-19.0,1054.0,1113,1008,65.0,NaN,0,0.0,...,1,0.0,ABI,0.0,N397AE,7.0,5.0,MQ,0.0,2005
1,43.0,19.0,12.0,850.0,838,745,53.0,NaN,0,0.0,...,1,0.0,BWI,0.0,N626AU,13.0,11.0,US,0.0,2005
2,65.0,31.0,26.0,1000.0,934,832,62.0,NaN,0,23.0,...,1,3.0,ATL,0.0,N845AS,6.0,28.0,EV,0.0,2005
3,40.0,17.0,84.0,1047.0,923,840,43.0,NaN,0,0.0,...,1,84.0,COS,0.0,N913SW,8.0,15.0,OO,0.0,2005
4,NaN,NaN,NaN,NaN,1110,645,205.0,B,1,0.0,...,1,0.0,AUS,0.0,0,0.0,0.0,CO,0.0,2005

In [29]:
origin_df = df.loc[df["Origin"] == "IAD"]
df_dest = df.loc[df["Dest"] == 'IAD']
frames = [origin_df, df_dest]

result = pd.concat(frames)

result

,ActualElapsedTime,AirTime,ArrDelay,ArrTime,CRSArrTime,CRSDepTime,CRSElapsedTime,CancellationCode,Cancelled,CarrierDelay,...,Month,NASDelay,Origin,SecurityDelay,TailNum,TaxiIn,TaxiOut,UniqueCarrier,WeatherDelay,Year
594507,177.0,164.0,-21.0,1329.0,1350,835,195.0,NaN,0,0.0,...,1,0.0,DEN,0.0,N829UA,3.0,10.0,UA,0.0,2005
594515,63.0,47.0,-6.0,1232.0,1238,1130,68.0,NaN,0,0.0,...,1,0.0,GSO,0.0,N652BR,5.0,11.0,DH,0.0,2005
594581,98.0,77.0,2.0,1338.0,1336,1155,101.0,NaN,0,0.0,...,1,0.0,BOS,0.0,N686BR,5.0,15.0,DH,0.0,2005
594619,85.0,65.0,-7.0,2000.0,2007,1840,87.0,NaN,0,0.0,...,1,0.0,ALB,0.0,N685BR,6.0,14.0,DH,0.0,2005
594812,108.0,74.0,10.0,1622.0,1612,1432,100.0,NaN,0,0.0,...,1,0.0,BDL,0.0,N391UA,4.0,30.0,UA,0.0,2005

In [31]:
result.to_csv('IAD_Airlines_2005.csv')

,ActualElapsedTime,AirTime,ArrDelay,ArrTime,CRSArrTime,CRSDepTime,CRSElapsedTime,CancellationCode,Cancelled,CarrierDelay,...,Month,NASDelay,Origin,SecurityDelay,TailNum,TaxiIn,TaxiOut,UniqueCarrier,WeatherDelay,Year
7,120.0,81.0,13.0,1117.0,1104,923,101.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N1799U,7.0,32.0,NW,0.0,2005
15,151.0,130.0,-14.0,2016.0,2030,1735,175.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N318UA,6.0,15.0,UA,0.0,2005
46,67.0,39.0,0.0,959.0,959,855,64.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N684BR,5.0,23.0,DH,0.0,2005
56,337.0,311.0,-4.0,1950.0,1954,1705,349.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N806UA,4.0,22.0,UA,0.0,2005
79,NaN,NaN,NaN,NaN,1823,1559,204.0,A,1,0.0,...,1,0.0,IAD,0.0,0,0.0,0.0,AA,0.0,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594676,85.0,66.0,10.0,1825.0,1815,1645,90.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N683BR,6.0,13.0,DH,0.0,2005
594683,67.0,36.0,28.0,1027.0,959,855,64.0,NaN,0,25.0,...,1,3.0,IAD,0.0,N660BR,4.0,27.0,DH,0.0,2005
594785,207.0,171.0,5.0,1037.0,1032,811,201.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N4XLAA,26.0,10.0,AA,0.0,2005
594847,290.0,262.0,4.0,1749.0,1745,1500,285.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N3765,10.0,18.0,DL,0.0,2005
594906,90.0,74.0,-21.0,2239.0,2300,2115,105.0,NaN,0,0.0,...,1,0.0,IAD,0.0,N654BR,5.0,11.0,DH,0.0,2005