In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
%matplotlib inline
from pathlib import Path
import pandas as pd
import scipy.stats as stats
import os

In [5]:
df = Path('../Data/airlines_2005_1.csv')

df = pd.read_csv(df)

df.head()

,ActualElapsedTime,AirTime,ArrDelay,ArrTime,CRSArrTime,CRSDepTime,CRSElapsedTime,CancellationCode,Cancelled,CarrierDelay,...,Month,NASDelay,Origin,SecurityDelay,TailNum,TaxiIn,TaxiOut,UniqueCarrier,WeatherDelay,Year
0,49.0,37.0,-19.0,1054.0,1113,1008,65.0,NaN,0,0.0,...,1,0.0,ABI,0.0,N397AE,7.0,5.0,MQ,0.0,2005
1,43.0,19.0,12.0,850.0,838,745,53.0,NaN,0,0.0,...,1,0.0,BWI,0.0,N626AU,13.0,11.0,US,0.0,2005
2,65.0,31.0,26.0,1000.0,934,832,62.0,NaN,0,23.0,...,1,3.0,ATL,0.0,N845AS,6.0,28.0,EV,0.0,2005
3,40.0,17.0,84.0,1047.0,923,840,43.0,NaN,0,0.0,...,1,84.0,COS,0.0,N913SW,8.0,15.0,OO,0.0,2005
4,NaN,NaN,NaN,NaN,1110,645,205.0,B,1,0.0,...,1,0.0,AUS,0.0,0,0.0,0.0,CO,0.0,2005

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594924 entries, 0 to 594923
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ActualElapsedTime  568031 non-null  float64
 1   AirTime            568031 non-null  float64
 2   ArrDelay           568031 non-null  float64
 3   ArrTime            568031 non-null  float64
 4   CRSArrTime         594924 non-null  int64
 5   CRSDepTime         594924 non-null  int64
 6   CRSElapsedTime     594924 non-null  float64
 7   CancellationCode   25085 non-null   object
 8   Cancelled          594924 non-null  int64
 9   CarrierDelay       594924 non-null  float64
 10  DayOfWeek          594924 non-null  int64
 11  DayofMonth         594924 non-null  int64
 12  DepDelay           569840 non-null  float64
 13  DepTime            569840 non-null  float64
 14  Dest               594924 non-null  object
 15  Distance           594924 non-null  float64
 16  Diverted           594924 non-null  int64
 17  FlightNum          594924 non-null  int64
 18  LateAircraftDelay  594924 non-null  float64
 19  Month              594924 non-null  int64
 20  NASDelay           594924 non-null  float64
 21  Origin             594924 non-null  object
 22  SecurityDelay      594924 non-null  float64
 23  TailNum            594924 non-null  object
 24  TaxiIn             594924 non-null  float64
 25  TaxiOut            594924 non-null  float64
 26  UniqueCarrier      594924 non-null  object
 27  WeatherDelay       594924 non-null  float64
 28  Year               594924 non-null  int64
dtypes: float64(15), int64(9), object(5)
memory usage: 131.6+ MB